### ISSUE TITLE
EOF makes an error when using the !! reader macro.

### ISSUE THREAD

**Issue by equwal** [Neronus/clesh#7]
I'm using SLIME in emacs. `!!` does cause an EOF error. Using the function `enter-shell-mode` manually is a workaround, or using SBCL directly in a terminal (without slime). It seems that slime is sending an EOF at the end of the line, rather than just a newline.

Probably need to change a call to `read-char` to have `(read-char str nil 'EOF)` or similar, since the default behaviour is to throw an error on EOF.

**Comment by Neronus** [comment]
Hey, I'm not really maintaining this anymore :(
Feel free to fork and fix :)

**Comment by Ambrevar** [comment]
The fix seems to be, in `read-interpolated-string`:

```diff
-       :for char = (read-char str)
+       :for char = (read-char str nil end-char1)

```

@Neromus: Do you still accept pull requests?  Otherwise, if I fork it, can you update the README to point to the new fork?

**Comment by Ambrevar** [comment]
By the way, I have the same issue with the `!` and the `#[` reader macros using SLY.

**Comment by Neronus** [comment]
I haven't looked at this code in years. I'll happily accept your pull request, though.

**Comment by vindarel** [comment]
Hello, I could reproduce the EOF error, but now with this commit the `!!` macro prints `$` forever. In Slime.

```
CL-USER> !!
$ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ $ ; Evaluation aborted on NIL.
```

**Comment by Ambrevar** [comment]
I'm not sure, but my guess is that the SLIME / SLY REPL input is never
ready.

Maybe we can try producing a simple read-eval-loop that works for SLY
and iterate from there.

Thoughts?

**Comment by vindarel** [comment]
Not sure either, I didn't look at the code. I tested in a readline application, without Slime, and it does the same.

edit: but this last commit is necessary for the simple bang `!` to work (otherwise it enters shell mode and doesn't evaluate shell commands until we type `!!`).

**Comment by Ambrevar** [comment]
In the SBCL REPL it works but the display is broken: the "$" is displayed after
the output and the user must press RET twice after "!!" to exit.
This is fishy.

Anyways, I wonder if this feature is useful at all considering `[`
works.  For instance you can do

--8<---------------cut here---------------start------------->8---
CL-USER> [echo foo
sleep 2
echo bar]
--8<---------------cut here---------------end--------------->8---

Shall we remove !! support?  I would make everything easier.
